### ISSUE TITLE
DHIS2 Docs: Update Screenshots for User Roles and Groups

### ISSUE THREAD

**Issue by Topener** [dhis2/hacktoberfest#12]
Repository: [https://github.com/dhis2/dhis2-docs/](https://github.com/dhis2/dhis2-docs/blob/master/src/user/manage-users-user-roles-and-user-groups.md)
Documentation Page: https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/configuring-the-system/users-roles-and-groups.html
App URL: https://play.dhis2.org/2.39dev/dhis-web-user/index.html (login is admin/district)

On the documentation page, the screenshots are outdated due to the release of the 2.39 version. The existing screenshots need updating based on the new looks.

**Comment by SaranshBaniyal** [comment]
@Topener can you please assign me this issue

**Comment by SaranshBaniyal** [comment]
@Topener can you please assign me this issue

**Comment by Topener** [comment]
Thanks for participating @SaranshBaniyal, I've assigned it to you!

**Comment by SaranshBaniyal** [comment]
can you please specify whether I have to update screenshots on this repo https://github.com/dhis2/dhis2-docs/blob/master/src/user/manage-users-user-roles-and-user-groups.md or this page https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/configuring-the-system/users-roles-and-groups.html

**Comment by Topener** [comment]
@SaranshBaniyal The Markdown files need updating, the HTML files are generated

**Comment by Topener** [comment]
@SaranshBaniyal once you've submitted the PR, please ping me there or ping me here!

**Comment by SaranshBaniyal** [comment]
ok thanks

**Comment by SaranshBaniyal** [comment]
Hey @Topener while taking screenshots, I came to know that for email invite options you need to configure SMTP email configurations in the System Settings, requiring a host name. I am not sure how to configure that. Can you please help me out, how should I proceed?

**Comment by Topener** [comment]
@SaranshBaniyal you could go 2 routes, one is to install the system yourself locally, through Docker for example, and go set up the SMTP settings there, or omit this screenshot for now. I will make note of that it will need to be changed in that case. 
Installation guides are here in case you want to go that route: https://developers.dhis2.org/docs

**Comment by SaranshBaniyal** [comment]
@Topener I don't think I'll be able to perform the installation route. I would be really grateful if you allow me to omit that part, I am ready to generate a PR, will it still be counted as a hacktoberfest--accepted PR?

**Comment by Topener** [comment]
@SaranshBaniyal yes it will still count for sure! Just mention in the PR which one is missing and I'll approve :)

**Comment by SaranshBaniyal** [comment]
Will do. Thanks a lot

**Comment by SaranshBaniyal** [comment]
@Topener I have submitted the PR. Thanks for all your support

**Comment by Topener** [comment]
@SaranshBaniyal thanks, we'll have a look at it!
