### ISSUE TITLE
DHIS2 Docs: Review & Update password requirements

### ISSUE THREAD

**Issue by Topener** [dhis2/hacktoberfest#13]
Repository: [https://github.com/dhis2/dhis2-docs/](https://github.com/dhis2/dhis2-docs/blob/master/src/user/manage-users-user-roles-and-user-groups.md)
Documentation Page: https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/configuring-the-system/users-roles-and-groups.html
App URL: https://play.dhis2.org/2.39dev/dhis-web-user/index.html (login is admin/district)

The password requirements have been updated, but this is not reflected in the documentation. This needs updating!

**Comment by adityaacse** [comment]
Hi @Topener I am interested in taking up this task. Please let me know the details about updates in password requirements.

**Comment by HendrikThePendric** [comment]
Password requirements are as follows:
 * At least 8 characters
 * No more than 34 characters
 * Contains at least 1 lowercase character
 * Contains at least 1 UPPERCASE character
 * Contains at least 1 number
 * Contains at least 1 special character

---

And username:
- At least 4 characters
- No more than 255 characters
- Lowercase and uppercase latin characters and numbers (`a-zA-Z0-9`)
- These characters are also allowed `.`, `_`, `@` and `#`, but these may only be used as a separator, so not as a leading or trailing character, and not repeating them (i.e. `user@@name` is not allowed)

If it helps, we're showing this validation message:
> Please provide a username between 4 and 255 characters long and possibly separated by . _ @ or #

**Comment by Topener** [comment]
Thanks @HendrikThePendric for providing an answer, should I assign the ticket to you @adityaacse?

**Comment by adityaacse** [comment]
Yes please

**Comment by Topener** [comment]
@adityaacse great, you're assigned! Please ping me on the PR once you're done!

**Comment by adityaacse** [comment]
@Topener I have made the changes as shown in screenshots, please confirm if this is good to create PR.
![username](https://user-images.githubusercontent.com/19973475/195126316-35f5b623-ee37-4369-a622-01756e1518a5.JPG)
![password](https://user-images.githubusercontent.com/19973475/195126387-4c3be131-a40c-476f-8f22-d40cbc1b7641.JPG)

**Comment by Topener** [comment]
Hi! That looks good @adityaacse, feel free to submit a PR and ping me when you've got it up! I'll make sure to validate it accordingly there

**Comment by adityaacse** [comment]
@Topener I have raised the PR against this issue, please review:
https://github.com/dhis2/dhis2-docs/pull/1089

**Comment by Topener** [comment]
Thanks @adityaacse for participating and submitting a PR
