### ISSUE TITLE
[LIBS-268] DHIS2 Application Platform: Show app and server version in fatal error boundary

### ISSUE THREAD

**Issue by Topener** [dhis2/hacktoberfest#9]
**Ticket** https://dhis2.atlassian.net/browse/LIBS-268
**Repository**: https://github.com/dhis2/app-platform/

Submit a PR to the repository and please mention the ticket number in the PR! Please follow the [guidelines](https://github.com/dhis2/hacktoberfest/blob/main/CONTRIBUTING.md)

**Comment by roldanbp** [comment]
Hey @Topener, i hope you are doing well!

Can I help you with this one?

Regards

**Comment by Topener** [comment]
Hi @roldanbp, of course! Feel free to pick this one up! Please mention in this ticket when you start working on it, and of course, ping me with any questions you might have
